### ISSUE TITLE
Online payment feature - integrate active merchant

### ISSUE THREAD

**Issue by rishabhs95** [openSUSE/osem#1105]
So as it turns out that integrating `active_merchant` to our codebase has some issues with itself.

Using `active_merchant`, we provide flexibility for organiser to choose a gateway of their choice. As we are not storing any type of Credit Card information to our database, it makes our application PCI compliant, but as the User’s credit card information will be transferred from our servers, it can make our PCI compliance fall in `SAQ-D` category.

To make it fall into SAQ-A, we need to use a service that moves the whole payment feature away from our servers. For this we have few options as :

- Use a paid service like [Spreedly](https://spreedly.com/pricing) that costs around $100/month, but provides us choice to choose the gateway from many of its supported gateways.

- Integrate a fixed payment gateway(like Stripe) which don't charge any monthly/yearly charges, directly to our application with options like https://stripe.com/docs/security#pci-dss-guidelines.

Please suggest what would be the best way to tackle this problem and move forward. @lagartoflojo @kalabiyau @differentreality @ChrisBr @hennevogel

**Comment by lagartoflojo** [comment]
There are different levels of PCI compliance. As soon as the credit card data even *passes* through our servers (let alone store it), we have to be compliant in the strictest and most expensive level (SAQ D).

There's a nice [summary here](https://blog.spreedly.com/2014/12/18/pci-dss-v3-0-for-online-merchants) for whoever is interested.

The easiest way to be PCI-compliant in an easy and cheap level (SAQ A) is to let an external service handle the CC data. That means embedding an iframe within our page that comes from that external service. (Stripe)[https://stripe.com/docs/checkout] and [Spreedly](https://docs.spreedly.com/guides/adding-payment-methods/express/) provide some JavaScripts that let us do that very easily and cleanly. But the thing is, we have to choose a service, because there doesn't appear to be a gem that will let us abstract that part away (like ActiveMerchant does).

Questions is, which service do we choose?

Spreedly costs some money, but it's not too much, and it will let the organizers choose from 100 different gateways, because it abstracts that part away. Meaning: the OSEM code requires no changes whether the organizer wants to get the money through PayPal or through Stripe.

Or we can directly implement a gateway that charges no additional fee, like Stripe, which limits the number of countries that the payment feature will work in.

**Comment by hennevogel** [comment]
The latter please: Stripe. Are you keeping in mind that OSEM is an application and not a service? We (in the sense of OSEM) don't have servers.

**Comment by lagartoflojo** [comment]
> Are you keeping in mind that OSEM is an application and not a service?

Right, which means that the PCI-compliance is the organizer's responsibility. But we have the choice of making it hard or easy for them :)

**Comment by hennevogel** [comment]
Is that really a choice? I don't think so... :-)

**Comment by rishabhs95** [comment]
Okay, then I am replacing `active-merchant` with Stripe iFrame for payments.
