### ISSUE TITLE
OSEM on Android: graphs continuously growing when I scroll

### ISSUE THREAD

**Issue by redimido** [openSUSE/osem#1195]
when watching the Admin panel from Android, everything looks fine.. just the graphs are put below the viewable area. not a issue in reality.

however when I try to go further down the graphs (registration, subimissions over time), my browser keeps becomes very slow and suddenly the graphs look bigger. I have not reached the buttons I was looking for, so I try again, and the same happens. I closed the browser when each donut graph was the size of my viewable screen on the tablet, and the browser was taking too much to do anything.

**Comment by differentreality** [comment]
I can reproduce.

**Comment by rishabhptr** [comment]
@differentreality Is this being solved elsewhere also because I can see a similar issue on mobile device for tickets sold page.

Please check this on mobile device after login.
http://demo.osem.io/admin/conferences/osemdemo/physical_tickets

While scrolling back and forth the page a couple of times, the white space around charts starts to increase infinitely, such that it is not possible to reach the end of the page.
