### ISSUE TITLE
Fix schedule creation when there are no room

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1209]
If there are not rooms you can create an schedule and then you see that:

![screenshot_20160926_135117](https://cloud.githubusercontent.com/assets/16052290/19007419/41f65174-8765-11e6-9d49-48fd27263522.png)

We should render something like that in the schedules page and not allow to create an schedule if there are no rooms, as this is quite confusing.

Also, the link to `Create rooms` doesn't work if there is not a venue. So, we should change it by `Create a venue with rooms` with a link to where the venue is created if there is not a venue.

**Comment by siddhantbajaj** [comment]
@differentreality in case you haven't started working on it, can I take up this issue?

**Comment by differentreality** [comment]
@siddhantbajaj go ahead :)

**Comment by siddhantbajaj** [comment]
yeah so I did something like this, If the venue is not added (obviously no rooms) then  it will show something like this

![osem1](https://cloud.githubusercontent.com/assets/17237680/21463862/c439443a-c995-11e6-9d8e-d5ec4eee2be6.png)

create venue and rooms,let us create venue but if we didn't  create the room we will get something like this ( on creating schedule )

![osem2](https://cloud.githubusercontent.com/assets/17237680/21463904/c397297e-c996-11e6-92e5-f2a879164ed9.png)

so just to enhance the user experience i think we should have a create room button somewhere in the create venue page itself or another approach could be every time we create a venue we are redirected to create room page so that user can create both rooms and venue in one go.
@differentreality review?
