### ISSUE TITLE
Fix Travis failures in a better way

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1286]
It used to happen something strange, after truncating the database and loading the seeds and before the first test is executed some data was introduced in the database. I have no idea of where this data comes from.

So this strange data kept there until a truncation was executed (after a feature). If a test query the information in the tables where strange data was introduced (for example User and Conference) before they were truncated it failed.

I added some puts here that illustrate what happened:

https://travis-ci.org/Ana06/osem/builds/191338450

This only happened in **Travis**, locally it worked.

To fix it the database was changed to truncate the database before each test in e4104ba2cdb84699ee2e83ee18b75a587b4c92ac

This is just a quick solution until we find out why was this happening. So, we should find a better solution to this problem and restore the database to it previous state, where the database was only truncate after a feature.

**Comment by siddhantbajaj** [comment]
I think the data  introduced in the db is because  we are Linting factories before each feature.

Linting before(:suite) reduces the performance of our test.  

 As suggested by Factory girl documentation we should be doing it in a separate task and should ensure that we clear the database  after linting the factories. 

@differentreality @Ana06 thoughts?
