### ISSUE TITLE
Issue with DeleteEventSchedules method

### ISSUE THREAD

**Issue by siddhantbajaj** [openSUSE/osem#1333]
I was playing around with conference start and end hour attribute when I found some issues related to DeleteEventSchedules method in conference controller. This method basically delete all EventSchedules that are not in the hours range of that particular conference. Issues that I found:
1. It deletes EventSchedules of all the conferences that are not in the hours range. Instead it should  delete EventSchedules of those events only that belong to that particular conference only.
2. If we set invalid start or end hour attribute of a conference then also EventSchedules gets deleted even though conference is not successfully updated.

For more information on DeleteEventSchedules method:
https://github.com/openSUSE/osem/pull/1143

**Comment by Ana06** [comment]
Good catch! :+1:

**Comment by GeorgiosKalantzis** [comment]
Hello , I am working on it , but because I haven't been accustomed with the OSEM application yet , can you help me about how to create events and put them in the schedule ? I have thoroughly searched it ,but I didn't figure out it . I will attach you a screenshot in order to specify in what exactly I have stucked. It's important , because I have modified the code in accordance with the demands of the issue , but I can't test it !..Thanks in advance !!
![screenshot_20170315_001052](https://cloud.githubusercontent.com/assets/26003969/23924885/4a1d7d82-0915-11e7-8e63-8c0dec9410e8.png)

**Comment by differentreality** [comment]
Events need to be confirmed in order to be made available for scheduling

**Comment by Ana06** [comment]
@GeorgiosKalantzis there is already a PR for this: #1334

please choose another issue in which there is not someone else working :wink:

**Comment by GeorgiosKalantzis** [comment]
Ok, It should have been told that someone else was working too , because I was ready to PR too, but it's I'll find something else !!
