### ISSUE TITLE
Grooming of openids in development

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1365]
* The mocks use emails with domain `email.com`, we should change that
* We should use similar name formats for the users created
* And we should also add relevant tests to prevent #1362

**Comment by AEtherC0r3** [comment]
I would like to work on this

**Comment by differentreality** [comment]
@AEtherC0r3 what's your progress on this?

**Comment by AEtherC0r3** [comment]
i've changed the usernamedomain to example.com and normalized. If you wish you can see the changes at https://github.com/AEtherC0r3/osem/tree/openid_improvements.

I hope to write the tests and open a pr by the end of the week.

**Comment by differentreality** [comment]
Please open a PR for us to review the changes, when you are ready.

**Comment by AEtherC0r3** [comment]
I think that the tests should include:
1. View tests to verify that the buttons for every provider are available in the root, signup and signin pages
2. Tests for signing up/in with every provider using the mock accounts

Since we don't have view tests anymore, no. 1 will not be implemented.

For no. 2, I found out that there are some macros defined in spec/support/omniauth_macros.rb.
So, should I
1. Edit the credentials of the existing mock accounts to make them similar to the credentials used in development and add new macros for the rest of the providers
or
2. Don't touch the existing macros and add a new one that includes all the mock account credentials from development
