### ISSUE TITLE
Ongoing conferences

### ISSUE THREAD

**Issue by siddhantbajaj** [openSUSE/osem#1367]
Currently ongoing conferences are shown under upcoming conferences on the home page. In my opinion there should be a separate section for ongoing conferences.

**Comment by differentreality** [comment]
Can you show me this with a screenshot?
Current and upcoming (future) conferences are shown in conference#index in chronological order.

**Comment by siddhantbajaj** [comment]
I was thinking of something like this:
![screenshot from 2017-03-15 17 18 47](https://cloud.githubusercontent.com/assets/17237680/23947194/b81a70cc-09a3-11e7-9649-7fecfa661b03.png)
![screenshot from 2017-03-15 17 19 15](https://cloud.githubusercontent.com/assets/17237680/23947207/c3a1e600-09a3-11e7-876d-23e946fc1800.png)

**Comment by differentreality** [comment]
What's your point? That we should not have the link and show everything since the beginning?

In my opinion, it is more confusing than helpful. In the majority of the cases, people will visit this page to do something about an upcoming conference, and not check on previous ones.

On a different note, we could place the date always one line after the conference title, so that its location is consistent for all conferences.

**Comment by Ana06** [comment]
@differentreality I think @siddhantbajaj means ongoing conference and not old conferences. And if that is the case that may be useful. :wink:

**Comment by differentreality** [comment]
Ah I see the point. Thanks @Ana06 
I am still not sure how much value it adds though. Perhaps after we implement the hosted version it will make some sense, but I am not super eager to implement this since now.

**Comment by siddhantbajaj** [comment]
@differentreality okay closing the issue. :wink:
