### ISSUE TITLE
Registration limit should not be less than count of registrations in conference

### ISSUE THREAD

**Issue by BelieveC** [openSUSE/osem#1447]
In conference, `registration_limit` attribute should be greater than equal to `conference.registrations.count`.

Scenario:

- Initially, conference have no restriction on registration
- 10 attendee registered for the conference
- Later admin want to add restriction on registration
- Registration Limit to the conference should be greater than equal to 10

Following update should raise an error

![rl](https://cloud.githubusercontent.com/assets/14261624/24785207/9080ee36-1b75-11e7-9b3e-8425829773f8.png)

**Comment by Ana06** [comment]
Not sure, for example speaker to register even after the Registration period is over because they will be there anyway. So, because of the same reason we should allow them to Register even if the exceed the Registration limit. Then introducing a validation should take this into account. :thinking: 

@differentreality @ChrisBr ideas?

**Comment by siddhantbajaj** [comment]
@Ana06 @BelieveC I had a discussion with @differentreality regarding this here #1347  and we decided not to add a validation for this. :wink:

**Comment by Ana06** [comment]
@siddhantbajaj 
> @Ana06 @BelieveC I had a discussion with @differentreality regarding this here #1347 and we decided not to add a validation for this. 

ok, then I'll close this! :wink:
