### ISSUE TITLE
Allow users to remove openid

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1468]
Currently a user can add multiple openids from the user Account settings. However those openids cannot be removed, they should.

**Comment by TeddySmoker** [comment]
Hey!

I want to get involved in FOSS and I recently found OSEM on up-for-grabs. I think this issue is fairly easy and I can do it myself, but I would like first to have a bit of guidance.

I have a rough idea of how to test it, similarly to the omniauth feature spec which tests the adding of openid to an existing user. 
But I don't really know where I should place the logic, should it be in the User model or Openid model? 

Thanks a lot!

**Comment by differentreality** [comment]
Hi @TeddySmoker ! If you are going to remove an openid, you are destroying a record of Openid model, so the openids controller should be handling that. Does that cover your question? Feel free to reach out through here, or IRC if you require more help.

**Comment by TeddySmoker** [comment]
Hey @differentreality, thanks for clearing that out.
I was guessing that it should be similar to a simple delete method, but all the time I was thinking of "Fat model, Skinny controller" and if I should place the logic in the model or not.

Again, thanks for clearing that out and I will give it a try to see how it works out, should be quite easy.

Cheers!

**Comment by differentreality** [comment]
@TeddySmoker are you working on this? What's your progress? Do you need help with anything?

**Comment by Colemalban** [comment]
Is this issue open now? If no one is working on it I would be interested.

**Comment by differentreality** [comment]
@Colemalban hi! I haven't seen any activity from @TeddySmoker for some time now, so I'd say you can go ahead and work on it.
