### ISSUE TITLE
User docs?

### ISSUE THREAD

**Issue by vmbrasseur** [openSUSE/osem#1633]
We're using OSEM for [SeaGL](http://seagl.org). It's my first year on the organising committee & I'm finding OSEM very difficult to use.

I've searched here and on osem.io, but I can't locate any user docs. Could you please direct me to them?

**Comment by differentreality** [comment]
@vmbrasseur if you have already been over our installation guide here, then probably not. We mainly try to guide you through the application to the next steps you need to take, but clearly not for what you want to do.
You can find the developers in #osem on freenode. I am also on #seagl channel. 
What are you looking for precisely?

**Comment by vmbrasseur** [comment]
User docs of any variety. Every time I try to do something in the software I end up having to use trial & error to puzzle it out. Having to ask just slows everything down further and is inefficient.

There's a lot more to software than just installation. I encourage OSEM to consider adding a user guide in the future.

**Comment by differentreality** [comment]
@vmbrasseur I agree, there is a lot more to it than just installation, specially with new features being added.

This is definitely something we want to do, the reason why I asked what in particular you wanted to know was because I want to help. The user guide will obviously not happen overnight. With seagl coming up in a couple of months (or so), I realize you want to get things going fast.

Additionally, knowing what troubled you will help us make sure we got those points covered in our guide, or focus on them more, or even pinpoint a part of the app that needs refactoring.

My 2 GSoC students will be adding a user guide for what they have done this summer in the next few weeks, and there is also https://github.com/openSUSE/osem/issues/1548 from another GSoC student of ours that will most probably be happening as well.
