### ISSUE TITLE
Fix Fixnum deprecated warnings

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1665]
Fixnum is deprecated

**Comment by ViditChitkara** [comment]
Can I take up this issue?

**Comment by faraazahmad** [comment]
While running `bundle exec rspec --color --format documentation`, the Fixnum deprecated warnings appear to be due to the dependencies of of the required gems, rather than the business logic itself.

For example, the monetize gem
```
/home/faraaz/.rvm/gems/ruby-2.4.0/gems/monetize-1.4.0/lib/monetize.rb:87: warning: constant ::Fixnum is deprecated
```
similarly, it also occurs in the `formtastic` and `simplecov` gems. The issue should be created on repositories of those gems IMHO.

Please correct me if I'm wrong.
Thanks

**Comment by AEtherC0r3** [comment]
For the upgrade to rails 5 #1714, I had to update formtastic, so the deprecation warnings that can be attributed to it have been fixed

**Comment by Ana06** [comment]
@AEtherC0r3 but are there still deprecation warnings or do you mean that we can close this? 🤔

**Comment by Ana06** [comment]
and Rails 5 PR is not still merged

**Comment by AEtherC0r3** [comment]
@Ana06 I've only fixed the `formtastic` related deprecation warnings in #1714. The ones that are caused by `monetize`, `simplecov` or other gems, are still there.

**Comment by bear454** [comment]
Resolved in https://github.com/openSUSE/osem/pull/1993
