### ISSUE TITLE
admin/physical_ticket#index should contain a amount paid option

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1682]
In case price for tickets change, then the admin should be able to see which User paid how much money.

**Comment by siddhantbajaj** [comment]
Yes actually a good feature to have because ticket price do gets changed a lot and there is early bird discount on tickets as well. But @rahul2240 what do you propose to achieve this? 
One possible approach could be having a "amount_paid" attribute in physical_ticket model so that we can store amount paid for that ticket. @Ana06 , @mdeniz your thoughts?

**Comment by rahul2240** [comment]
@siddhantbajaj I was thinking the same.

**Comment by differentreality** [comment]
All that (ticket, physical_ticket, etc.) should be linked with payment in the end. Payment does hold the amount info. So we should be able to extract how much users have paid, based on the type of ticket they have purchased. Isn't that so?

**Comment by rahul2240** [comment]
I was thinking to create a new column in purchase_ticket model and if the payment is done then before rendering physical ticket, the price of the ticket can be stored in the amount_paid column.right now i am doing this , if this is not the correct way then please let me know.

**Comment by differentreality** [comment]
I am not sure I understand **why** we need the new column. Why are we not extracting the amount information from payments table?
Maybe I am missing something in our tickets workflow.

**Comment by Ana06** [comment]
@differentreality 

> I am not sure I understand why we need the new column. Why are we not extracting the amount information from payments table?

Because in payment we have the total amount, so if you buy 3 different tickets it is impossible to know what is the price of every ticket.

However, I am not pretty sure if including the new column in `physical_ticket`, as @rahul2240 and @siddhantbajaj suggested, is the best option. Why not in `ticket_purchase`?
 Currently we are delegating this to the ticket, but as the price could change after payment, that doesn't make sense for me: https://github.com/openSUSE/osem/blob/master/app/models/ticket_purchase.rb#L14
