### ISSUE TITLE
getting error on get more ticket option 

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1700]
Getting this error when i try to buy more tickets. When only 1 event is there and the user already bought the ticket for the conference, then either get more ticket option should be hidden or the continue button on the ticket purchase screen should be locked.
![new1](https://user-images.githubusercontent.com/25618739/30510860-64b8bad2-9aea-11e7-95f5-6133aa7eb817.png)

**Comment by rahul2240** [comment]
I think it is fixed in some pr ,because i am also not able to reproduce this now.

**Comment by rahul2240** [comment]
@differentreality  create a ticket and tick the registration ticket required option.After buying that ticket, you will not be able to buy more ticket as the quantity option will be freezed, and if you go to continue then you will see this error.

**Comment by differentreality** [comment]
OK got it, thanks!

I agree, it is confusing. If I can only buy a registration ticket (no other kind), and I have already bought one, there is no point seeing the tickets#index page at all.

**Comment by rahul2240** [comment]
@differentreality  i think everything is fine on this page , we just need to disable the continue button if all tickets are bought by the user. Let me know if you agree?

**Comment by differentreality** [comment]
To be honest, I wouldn't redirect users on a page there is nothing for them to do. 
Users get there from the 'Get more tickets' button in the registration page (conference_registrations#show). 

This is what should be disabled, in my opinion. And with a short explanation as to why this button is now disabled.

**Comment by rahul2240** [comment]
Yes i think you are right,user should not be redirected to that page.I will do it, Thanks

**Comment by rahul2240** [comment]
@differentreality While fixing this issue, i got some more. I think i didn't properly understand  the use of registration ticket while creating a ticket.Please tell me why we need that option and when we need that option to be ticked and when not.

**Comment by differentreality** [comment]
Introduced in https://github.com/openSUSE/osem/pull/1627 a registration ticket is the ticket you will use to register to the conference (register in person when you arrive). For open source conferences there is usually no cost to attend, so this ticket could be of 0 amount, still you would get the ticket, and present it upon your arrival, so that it can be scanned and you may be marked as attended.

Now you may buy other tickets, such as a ticket to support the conference (eg supporter ticket, which may or may not have extra benefits, like get you to a dinner), or another ticket to attend a specific workshop for which you have to pay extra. While this is not very common in open source conferences, I hope it helps you understand.

That said, if you are stuck somewhere you will need to show us a screenshot of the error(s) you get, and preferably push the failing code to this PR so that we can check it on our own and help you figure things out. 

Do you already have a written workflow of what you are trying to achieve?

**Comment by rahul2240** [comment]
@differentreality Thank You 😄 . I was trying to remove the get more ticket option when a user already bought all the tickets for the conference. But i found if i buy a ticket for a event (where registration ticket is required) then i cannot buy tickets for other events (where registration ticket is required) as they get disabled and i can only buy ticket for the event (where registration ticket is not required).

This means that user cannot register for more than 1 event where registration ticket is required.

**Comment by differentreality** [comment]
Well perhaps something is wrong with the condition you are using? I can't know unless I see your code.

I asked this before: Do you have a clear written implementation plan which you are following? If so, please share it with us, along with the code that is giving you trouble, so that we can help you out.

**Comment by rahul2240** [comment]
@differentreality I will add screenshots. 
What i did was, i created a conference then created 2-3 tickets  and marked the registration ticket option.Then i signed in as a user and bought 1 ticket for a event then i came back to home page , now i again click on registration then get more ticket then i found that all 3 tickets were disabled.

**Comment by rahul2240** [comment]
@differentreality should i open a separate issue for this?

**Comment by differentreality** [comment]
@rahul2240 not sure what _this_ refers to.

**Comment by rahul2240** [comment]
@differentreality  There are 2 type of tickets-
1) Where registration ticket is required (i.e only 1 ticket per user )
2) Where registration ticket is not required (i.e any number of ticket per user)

for the first type, on buying 1 ticket for a event other tickets of first type gets disabled.

I am facing problem because of the above issue as other ticket are getting locked.

If i try to ignore this and focus on this issue, i can only do one thing i.e counting different tickets that are available and counting different tickets that are bought by user, i dont think this is a good way.Can you suggest?

**Comment by differentreality** [comment]
Did you buy 1 **registration** ticket?

The conference should have only 1 registration ticket, right @Ana06 @siddhantbajaj ?

**Comment by rahul2240** [comment]
Yes i bought 1 registration ticket.

**Comment by differentreality** [comment]
Then you cannot buy another registration ticket. The disabled tickets are all registration_tickets. 

I think this issue might be due to the fact that 1 conference can only have 1 registration_ticket, but we allow the organizer to create multiple registration tickets. 

I'd wait for @Ana06 and @siddhantbajaj to confirm this.

**Comment by rahul2240** [comment]
@Ana06 @siddhantbajaj  please see the issue.

**Comment by siddhantbajaj** [comment]
Sorry for the late response, I was busy with my exams. A registration ticket is the one that is used for check-in for a conference with the help of qr code. A conference can have multiple registration tickets because it is very common for conferences to have different types of free and paid tickets. But registration are used only for the check in for a conference. They belong to a conference not to any particular event. @rahul2240 why did you create a registration type ticket for an event? A user can only have one registration ticket that will be used for the marking the user present. For events create separate non registration ticket. Yes I know it lacks documentation so I will soon create a PR for this.

**Comment by differentreality** [comment]
Is there anything else to do here for this? Can we close it? @rahul2240 @siddhantbajaj

**Comment by Ana06** [comment]
@siddhantbajaj can you create an issue for the documentation? just in case you don't have time someone else do it.

**Comment by bear454** [comment]
Resolved in https://github.com/openSUSE/osem/pull/2000
