### ISSUE TITLE
Payment for tickets are still possible after conference end date

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1735]
User can still make payment and edit purchase if there were any unpaid tickets even after the conference has ended.

**Comment by bear454** [comment]
I can think of valid use cases for allowing payment after-the-fact. What's the argument for blocking it?

**Comment by differentreality** [comment]
@bear454 could you share some of the use cases you can think of?

**Comment by differentreality** [comment]
@bear454 in my experience tickets are bought prior to events, and donations are made during the event. 
What's the scenario you are thinking for a conference that gets payments after it is over? 
I could think of late sponsorship payments, if they would want to do the payment this way instead of bank transfer.

**Comment by bear454** [comment]
@differentreality that's mostly what I was thinking of - late sponsorship payments. WRT other cases, paying late is better than not paying ;-)

**Comment by differentreality** [comment]
OK let's leave it as is then!
