### ISSUE TITLE
Consider changing junior label

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1768]
Github will use good first issue label to help new contributors to find issues.

![image](https://user-images.githubusercontent.com/16052290/31668436-8077a082-b352-11e7-8c2a-8a1100a7bc21.png)

Do we want to rename our `junior` label to be `good first issues`? :thinking:

**Comment by Ana06** [comment]
@differentreality @ChrisBr what do you think?

**Comment by differentreality** [comment]
I've seen that from github too, and I've also been wondering if we can make any changes.
`help wanted` is too general, and does not really convey the message that this issue is good for a first-timer. 
`good first issue` is much better, but perhaps I wouldn't put all of our junior issues under this label. We have junior issues that are easy to do, but not necessarily the first thing one should work on for the first time. 

Writing this, I am thinking `good first issue` label could be added, and we label as such the junior jobs that are really really easy and for first timers, while we keep the junior label as well.

**Comment by Ana06** [comment]
then I'll add the good first issue label and keep the junior one as well 👍
