### ISSUE TITLE
Commercials do not accept a SlideShare URL

### ISSUE THREAD

**Issue by ftake** [openSUSE/osem#1775]
The URL input field on the Commercial tab does not accept a URL of SlideShare.
The following error message is shown

```
No embeddable content at 'OEmbed::NotFound'
Just paste the url of your video/photo provider. Currently supported: YouTube, Vimeo, SpeakerDeck, SlideShare, Instagram, Flickr.
```

Tested with the following URL: 
https://www.slideshare.net/ftake/welcome-to-opensuseasia-summit-2017

**Comment by differentreality** [comment]
I can confirm this is not working :'(

**Comment by cho2** [comment]
https://events.opensuse.org/conference/summitasia17/program/proposal/1502

It works with SlideShare with `http` instead of `https`

**Comment by Ana06** [comment]
We already knew this issue, because in the last openSUSE conference there were instructions to remove the `s`. Not very nice :see_no_evil: 

Isn't there an issue for that?

I think @ChrisBr tried to fix it. If we can't easily fix it, maybe removing automatically the s in production, at least to make it work by now... :thinking:

**Comment by rishabh92** [comment]
Looking into this bug. Will issue a PR when done.
