### ISSUE TITLE
 autofill CFP end date

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1872]
## Description

For every date you choose for the beginning for a CFP, when you go to choose the ending date it always show the current month.

It could be good that the behaviour for the ending date show at least the same month where the cfp starts. 

- **old behaviour**

![old-behaviour](https://user-images.githubusercontent.com/5561794/33796264-e04709d6-dcd7-11e7-99f8-4d6910ff4db9.gif)

### Steps to Reproduce

1. register a new CFP
2. select start date from the calendar (any month ahead which isn't the current one)
3. select the end date - it will be showed the current month

**Expected behavior:** after the beginning date was defined, calendar for end date starts showing at least the same one as showed in the start date

![new-behaviour](https://user-images.githubusercontent.com/5561794/33796289-6b694358-dcd8-11e7-9b5e-ae901af0298a.gif)

**Reproduces how often:** I reproduced it every time I've tried.

**Version:** I've tried against master branch

**Comment by differentreality** [comment]
Thanks for picking up those UI fixes @adrianovieira :+1: 

Please prefer to wait for issues to be labeled by the maintainers. 
That way we can avoid duplicate issues and PRs, as well as features we are not ready to accommodate. 

While this is not the case with this issue and respective PR (which is also very small, so perhaps this wouldn't apply at all anyway), there are other examples that work is duplicated, or features are misunderstood. 

Also please leave a comment that you are working / are going to work on an issue, so that others know not to pick it up!

_This does **not** imply you should close this issue or your PR._
