### ISSUE TITLE
Migration change_visit_id_type_of_ahoy_events_to_integer crash

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#1885]
Doing a rails db:migrate in a current working installation doesn't work because some data in the db

db/migrate/20171118113113_change_visit_id_type_of_ahoy_events_to_integer.rb

```
Mysql2::Error: Incorrect integer value: '\xB1\xC1\x14k4\x02L\xD7\xAD5Mvy\xE4\x94\xB2' for column 'visit_id' at row 1: ALTER TABLE `ahoy_events` CHANGE `visit_id` `visit_id` int
/vagrant/db/migrate/20171118113113_change_visit_id_type_of_ahoy_events_to_integer.rb:3:in `change'
bin/rails:6:in `require'
bin/rails:6:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect integer value: '\xB1\xC1\x14k4\x02L\xD7\xAD5Mvy\xE4\x94\xB2' for column 'visit_id' at row 1: ALTER TABLE `ahoy_events` CHANGE `visit_id` `visit_id` int
/vagrant/db/migrate/20171118113113_change_visit_id_type_of_ahoy_events_to_integer.rb:3:in `change'
bin/rails:6:in `require'
bin/rails:6:in `<main>'
```

**Comment by differentreality** [comment]
@AEtherC0r3

**Comment by AEtherC0r3** [comment]
If we were to recreate ahoy's migration with `rails generate ahoy:stores:active_record --force`, the visit_id column's type would be specified as integer. The id column of the visits table is an integer, therefore, I'm not certain if the visit_id column contains any meaningful data. (because it's type was uuid/binary and ahoy's README states

> Use the uuid column type if the id column on visits is a uuid 

which is not the case).

If we can test, in a definitive way, if the data in that column is meaningful or not, and we find out that it isn't, then we can modify the migration to drop and recreate the column. When, someone pulls the modified code from master, the following two scenarios are possible:
1. The old version of the migration had run and the column contains junk data, no harm done.
2. The modified version runs and the column is empty, no problem either because there is no not null constraint.

Another, cleaner, solution would be to remove the faulty migration, drop the ahoy_events and visits tables and recreate them. Since, they are supposed to contain analytics related data, I wouldn't consider them to be "mission critical".

@hennevogel @ChrisBr @differentreality @bear454 @lagartoflojo @Ana06 What's your opinion about how this should be handled/fixed?

**Comment by captn3m0** [comment]
Facing this while upgrading an existing installation to latest master.

```
Migrating to ChangeVisitIdTypeOfAhoyEventsToInteger (20171118113113)
== 20171118113113 ChangeVisitIdTypeOfAhoyEventsToInteger: migrating ===========
-- change_column(:ahoy_events, :visit_id, :integer, {:limit=>nil})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Incorrect integer value: '\x89\xB6\xBCu\x81\xD1D\xA3\xAD\x04\x1A\xDC\xCAWb2' for column 'visit_id' at row 1: ALTER TABLE `ahoy_events` CHANGE `visit_id` `visit_id` int
/osem/db/migrate/20171118113113_change_visit_id_type_of_ahoy_events_to_integer.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect integer value: '\x89\xB6\xBCu\x81\xD1D\xA3\xAD\x04\x1A\xDC\xCAWb2' for column 'visit_id' at row 1: ALTER TABLE `ahoy_events` CHANGE `visit_id` `visit_id` int
/osem/db/migrate/20171118113113_change_visit_id_type_of_ahoy_events_to_integer.rb:3:in `change'

Caused by:
Mysql2::Error: Incorrect integer value: '\x89\xB6\xBCu\x81\xD1D\xA3\xAD\x04\x1A\xDC\xCAWb2' for column 'visit_id' at row 1
/osem/db/migrate/20171118113113_change_visit_id_type_of_ahoy_events_to_integer.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Managed to bypass this by setting visit_id to zero and forcing it to int

**Comment by yagudaev** [comment]
Any updates on this? Facing the same challenge

**Comment by bear454** [comment]
As a workaround, if possible, you can delete all records in `ahoy_events` table.

**Comment by hennevogel** [comment]
As Captain of this vessel, seaman and inventor of this feature, I don't like to say this, but: Ahoy must die.

**Comment by bear454** [comment]
@hennevogel : does that mean campaigns go away? I'm all for that - we've had better success running such stats through client analytics (ga or matomo).

**Comment by differentreality** [comment]
For what it's worth, the new version of ahoy (which we already have https://github.com/openSUSE/osem/pull/2006) seems to be working fine. It's this particular migration that wasn't bulletproof.

**Comment by hennevogel** [comment]
@differentreality sure, it's working but do you think anyone is using this feature? I don't know of anyone...

**Comment by bear454** [comment]
I'll take this; I already have some code in LFNW for dropping Ahoy...
