### ISSUE TITLE
NoMethodError in ConferencesController#show 

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1962]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Getting error when splash page is not present.

![splash](https://user-images.githubusercontent.com/25618739/34888767-7fd0ea10-f7f1-11e7-8130-dec952bf9a06.png)
![splasherror](https://user-images.githubusercontent.com/25618739/34888771-8482832a-f7f1-11e7-863f-e2a1cd87872f.png)

**Expected correct behavior:**

Clicking on splashpage link should redirect user to create splashpage if splashpage is not present else it should redirect to splashpage.

**Steps to reproduce:**
1. Create conference
2. Go to splashpage
3. Click on splash page link (Build a "splash page" with all the information for your conference )

**Comment by AnkushMalik** [comment]
just for good ux ,may be instead of taking user to create splashpage , that link should direct user to some info page describing what splash page is, in a new tab . Like markdown Syntax link under every desc field : 
![screenshot-2018-1-13 osem](https://user-images.githubusercontent.com/13421233/34908103-9b461c24-f8b0-11e7-8bcb-5438a47e0bff.png)

Or even we can remove that link since theres already a bigger button on the page :thinking:

**Comment by differentreality** [comment]
@rahul2240 it would be useful to know that you need to not be an admin user, but not be a simple user either. To reproduce this you need to be allowed to access the splashpage, so your user needs to be the organizer of the conference (or similar user access to the action conferences#show even when there is no splashpage).

**Comment by ankitbhardwaj78** [comment]
@differentreality can i claim this issue??

**Comment by differentreality** [comment]
sure @ankitbhardwaj78

**Comment by differentreality** [comment]
The error still exists for show template

![screenshot from 2018-02-23 12-07-27](https://user-images.githubusercontent.com/4322737/36589193-32a370b0-1893-11e8-99c3-b84376028bc5.png)

**Comment by dPliakos** [comment]
Can I work on this issue?
