### ISSUE TITLE
iCal Link for Schedule

### ISSUE THREAD

**Issue by sumnerevans** [openSUSE/osem#2147]
**I'm submitting a Feature Request**

I would like to have an iCal calendar endpoint which has the event schedule. That way I can import it into Google Calendar and have it synchronized with the actual schedule.

# Questions
- I am willing to work on this feature, but I am a terrible UX designer. Is there anyone who can help me with that aspect?
- I would like to have this general idea approved before trying to implement it. Is there a process for getting such approval?

# Implementation Notes
- I've done something similar with our club website by exposing an endpoint: https://acm.mines.edu/schedule.ics and procedurally generating the iCal calendar from the schedule ([link to code](https://github.com/ColoradoSchoolOfMines/mozzarella/blob/master/acmwebsite/controllers/schedule.py#L35)).
- Google caches iCal calendars, so it may take up to a day for a linked calendar to update. For testing purposes, just manually download the iCal file and import it, rather than subscribing to the URL via the Google Calendar interface.

**Comment by logological** [comment]
I assume this feature request is asking for there to be links on the schedule to events in iCalendar format. (iCal is not a format but rather the name of a calendar application, marketed by Google, that uses the iCalendar format.)  If so, then I support this request, since iCalendar is an open format that is used by many free software Calendar applications (including Thunderbird, which is what I use).  I don't think that OSEM should cater specifically to Google Calendar, though this won't be necessary since Google Calendar works with iCalendar files anyway.

**Comment by sumnerevans** [comment]
Yes, I was referring to iCalendar files (extension: `.ics`).
