### ISSUE TITLE
Forget Password not working

### ISSUE THREAD

**Issue by ramsiddu007** [openSUSE/osem#2258]
**I'm submitting a ..**
Bug Report
- [x] Feature Request

**Current behavior:**

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by differentreality** [comment]
@ramsiddu007 Please fix the description of the issue and let us know where this has occurred.

**Comment by ramsiddu007** [comment]
I am trying to submit my email in forgot password screen in www.pgconf.in, it seems error. Please rectify it.

**Comment by differentreality** [comment]
OK but which part isn't working? Do you submit your email successfully? Do you receive an email afterwards? Can you visit the URL in the email? Do you enter a new password successfully? Is the new password not working?

That said, I cannot reproduce the error with the current master, why did you submit an issue here instead of contacting the organizers of the conference?
