### ISSUE TITLE
Form dates are always in read only mode

### ISSUE THREAD

**Issue by lbenore** [openSUSE/osem#2455]
After creating a new conference you are unable to setup the registration period because the start and end dates are always set to read only. The track dates have the same issue the start and end dates are always set to read only.

![image](https://user-images.githubusercontent.com/28565816/54834027-eac9d280-4c84-11e9-8713-b3df7ec1ce2b.png)

**Comment by cyrillefr** [comment]
Hello, 
I came across the same issue these days too, regarding the "Registration period" form.
The component does not show up because of the readonly attributes defined in the haml form.
The problem lies in the app/assets/javascripts/osem-datepickers.js file.

There are typos while instantiating the component:
`$('#registration-period-start-datapicker').datetimepicker({ ...`
It should be datepicker instead of datapicker.
I hint there is a similar problem with call for paper since there is a similar typo.(But in a haml form this time).

But there is the readonly attribute that prevents the input to be updated. Getting rid of the readonly attribute will allow that, however it will possible to put a non valid entry in that input.
My suggestion would be to keep the readonly but, to pass an ignoreReadonly at the inception of the Bootstrap datepicker component in JavaScript, that allows change of date but prevents to enter manually a non valid date.

After some changes in the code, I have also noticed JS errors (calls on  mispelled methods on datepicker).

I volunteer for this issue since I have already done some work on it.
I can check for cfp, tracks and conference since they are using the same datepicker component.

**Comment by Ana06** [comment]
@cyrillefr go ahead!

@rahul2240 you wanted to do some related work as well, although I though that where improvements and not broken stuff. Please be careful not to work on the same as @cyrillefr (you can also review his PR when he send one and work together to fix all the problems) :wink:

**Comment by rahul2240** [comment]
@Ana06 Yes, I was talking about the broken stuff :sweat_smile: I thought I was not allowed to make those changes so I dropped those commits, but I can help in reviewing the code. Thank you :smile:

**Comment by lbenore** [comment]
@cyrillefr I also noticed the datepickers on the program page for the voting dates has the same issue.

![image](https://user-images.githubusercontent.com/28565816/55006753-ddbe2380-4fa3-11e9-9c59-d650d6d10b26.png)

**Comment by cyrillefr** [comment]
Thank you @lbenore, you are right. I have looked after this part too.
