### ISSUE TITLE
fonts broken

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#428]
Hi,

We have these weird looking characters:
![broken1](https://cloud.githubusercontent.com/assets/551757/3791103/b1bfb320-1b28-11e4-9aaa-f6d241690db6.png)

@gopesht says it isn't a joke you folk were pulling, so it's an issue then ;-)

**Comment by redimido** [comment]
Basically I had the same issue, but in order to have the icons corrected, I ran:
```
RAILS_ENV=production bundle exec rake assets:clean
RAILS_ENV=production bundle exec rake assets:clobber
RAILS_ENV=production bundle exec rake assets:environment
RAILS_ENV=production bundle exec rake assets:precompile

```
restarted nginx, and that did the trick.

Also for the case when osem is under a subsite, I had to catch the images referring to /assets and redirect them to the correct subsite folder name.
Perhaps this can be requested as a feature?
