### ISSUE TITLE
Longitude and Latitude seems be reversed 

### ISSUE THREAD

**Issue by Doctor-Who** [openSUSE/osem#664]
On admin menu > edit venue > longitude and latitude seems not work well on the splashpage.
I've got to reverse coordinate to have right place on OSM map preview.

**Comment by differentreality** [comment]
@Doctor-Who I suppose that's because you immediately knew which one was which, I have been kinda copying first number of googlemaps into our first field, second number of googlemaps into the second field.
Which works, right?
It's just a matter of label text!

**Comment by Doctor-Who** [comment]
I reinstall a fresh instance of OSEM and still have same problem.
I've got to insert longitude in latitude field and latitude in longitude to have correct location map.
For example Amiens is Latitude 49.895 and Longitude 2.3022 but in OSEM, i've to indicate 2.3022 in Latitude field. 
Careful, using . and , change location, OSM and Google API attend . for decimal. Should add a verification step when user enter coordinate ?

**Comment by differentreality** [comment]
You can't see the changes because the changes are not merged into our master yet. 
We first asked you, to double check the fix was properly working. But in order to try out the fix, you would need to checkout the changes in #681 

Anyways to make this easier, since my PR was reviewed by Chris, I will merge it and you can update your master to see the change. Then you can let us know if it looks OK?

Thanks a lot for reporting this!

**Comment by Doctor-Who** [comment]
It works perfectly now, thanks for your effort :+1:

**Comment by differentreality** [comment]
Fixed in #681
