### ISSUE TITLE
proposal subtitle and difficulty only shown during /edit

### ISSUE THREAD

**Issue by meonkeys** [openSUSE/osem#675]
Perhaps this was intentional (if so, what's the intent?), but proposal subtitle and difficulty are only shown during `/edit`.

Here's the `/edit` page:

![subtitle and difficulty only when editing](https://cloud.githubusercontent.com/assets/50639/8144836/2161055e-11a4-11e5-933a-a7a571a55b07.png)

And here's the `/new` page:

![screencapture-osem-seagl-org-conference-seagl2015-proposal-new-1434208695590](https://cloud.githubusercontent.com/assets/50639/8144854/edfd8bdc-11a4-11e5-9025-dfb782b87beb.png)

**Comment by differentreality** [comment]
Yep that is intentional indeed, so that when you are prompt to the proposal form for the very first time we don't overwhelm you with a lot of information, just the required one. That's in the concept of keeping it simple and fast for speakers to submit their proposal.

Then, if you want to add more stuff, you edit the proposal and you have a lot more options (which could be filled out after the proposal is accepted).

**Comment by meonkeys** [comment]
Ah ok, makes sense. Thanks!
