### ISSUE TITLE
Blind voting

### ISSUE THREAD

**Issue by meonkeys** [openSUSE/osem#702]
Feature request: add a checkbox to event configuration to hide other's ratings (and possibly also hide the fact they voted at all).

This came up during SeaGL 2015 voting. It would be handy to be able to _not_ see others' ratings (or even that they voted) while doing your ratings/votes.

**Comment by hennevogel** [comment]
The reasoning for this is? That you don't follow the herd? :-)

**Comment by meonkeys** [comment]
LOL, I guess not.

I just thought it would be nice to have at least one round of SeaGL voting
unbiased by peer organizers.

**Comment by hennevogel** [comment]
Hm so this should be a config option you can enable/disable?

**Comment by altsalt** [comment]
I would highly recommend/suggest this feature!

Academic conferences require blind voting for the sake of fairness; this extends to not event knowing the presenter's name.

Large conferences may want both types of blinds first round so that friend/group bias does not occur. They may want to continue with the option of having a second round which is blind to other's votes to maintain the protection against group bias.

This could lead to the wider discussion of a front-end, or at least more clear, template configuration.

**Comment by meonkeys** [comment]
@hennevogel yes (@altsalt said it well)

**Comment by differentreality** [comment]
So the idea is that a user that has access to see/vote on available proposals does not see who voted, the vote of other people, or the average voting of the proposal.

Until when? 
* until after the user votes (but the user can change his/her vote at any time)
* until voting period is over (then we can show all voting details and disallow any voting changes)

**Comment by ChrisBr** [comment]
I would go for the latter!

**Comment by ChrisBr** [comment]
And as next step I would also hide the submitter name as @altsalt suggested! 

@differentreality do you plan to work on this the next time?

**Comment by differentreality** [comment]
Yes, I will work on it.

**Comment by altsalt** [comment]
Yay!
