### ISSUE TITLE
Proposal Page Formatting

### ISSUE THREAD

**Issue by altsalt** [openSUSE/osem#731]
As the main information is the proposal itself, not the speaker, why not flip which one lives in the sidebar and which in the main?

**Comment by differentreality** [comment]
you are referring to proposal#show I guess.

**Comment by chocoelho** [comment]
But isn't it shown in the header? I mean, proposal title and sub title are not in the sidebar.

**Comment by hennevogel** [comment]
The speaker info is below the Commercial and the Talk info on the left of it. We could switch this

**Comment by alexdor** [comment]
Hi everyone,

I've tried tackling the above issue with this commit b7bba4ba44a371c3b62fab4aba40355c6e9b7194. 

I tried displaying the date, duration, room etc. with many layouts but because there are seven of them there was always one that was remaining alone so I decided to display them as a list. Is there any other suggestion about who to group them? 

Also, I made a minor css change in order to display the context correctly so I made it at osem.css.scss, should I place it somewhere else?
