### ISSUE TITLE
UI doesn't allow registration period dates in future

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#798]
Steps to reproduce:
* Make a conf with date in future (say 16 March, 2016)
* Go to registration period page (`http://localhost:3000/admin/conference/<conf_short_title>/registration_period`)
* Click new registration period button
* Try to pick a date in future (after today. say 2 March, 2016)

Dates after today are unselectable. I don't think this is desired behavior.

Mentioned issue goes away if `useCurrent: false` is set in these [lines](https://github.com/openSUSE/osem/blob/37697517df1a34a5d62773713307a93a0039d98a/app/assets/javascripts/osem-datepickers.js#L45-L54):
```Js
$("#registration-period-start-datepicker").datetimepicker({
      format: "YYYY-MM-DD",
      pickTime: false,
      pickSeconds: false,
      useCurrent: false
  });
  $("#registration-period-end-datepicker").datetimepicker({
      format: "YYYY-MM-DD",
      pickTime: false,
      pickSeconds: false,
      useCurrent: false
  });
```

**edit:** fix link of line numbers.

**Comment by differentreality** [comment]
Just for clarity I would like to add that the reason why the future days are not clicable is because when we click once on the field, the calendar pops up, and it also pre-selects Date.today as the start_date and end_date. Since the end_date is now selected by default to Date.today, the start_date cannot be after the end_date: that validation disallows the selection of future dates.
