### ISSUE TITLE
Short title validation feedback to user when creating a conference

### ISSUE THREAD

**Issue by arun1595** [openSUSE/osem#819]
To reproduce:
      Create a new conference filling in all the fields.(http://localhost:3000/admin/conference/new)
      Click Create Conference.
[Stacktrace here](http://paste.opensuse.org/75943850)
@conference.program is nil
So getting a undefined method id for nil:NilClass when trying to access conference.program.id

**Comment by differentreality** [comment]
@arun1595 the title says that the conference is created and the program is not created. However from your code it seems that the conference was **not** created, due to invalid data. Can you confirm?

In addition fix the link with your code so that we can click on it and add **all** the available log of this action, there is more code before what you pasted.

**Comment by arun1595** [comment]
@differentreality Yeah, the conference was not created. I should have named it as "when trying to create a conference". The conference was not created due to an error **short title is invalid**
The issue was with the validation of short title with the regex /\A[a-zA-Z0-9_-]*\z/
I entered a short title with spaces. Since the regex doesn't allow spaces, I got an error.
I think we should provide the conference creator feedback as to why the error happened. Or else we can add client-side validation checking whether the user has used a space when adding a short title.

[https://gist.github.com/arun1595/83912a96ddf31f1fdc7a](url)

**Comment by differentreality** [comment]
Fix your links! Please!

**Comment by arun1595** [comment]
@differentreality Updated the links

**Comment by ChrisBr** [comment]
@arun1595 as @differentreality already stated out, it seems creating a new conference doesn't create a program.

Usually you should get a flash message that the short title is invalid, this doesn't happen because of the program issue. Implementing feedback on the client side is an enhancement / feature, please create a new issue for it!

**Comment by ChrisBr** [comment]
@arun1595 creating a conference works for me!

**Comment by ChrisBr** [comment]
Also creating a conference with an invalid short title displays correct flash message 
``
Could not create conference. Short title is invalid 
``

**Comment by ChrisBr** [comment]
Validation of the short title with javascript is an enhancement, changed labels!

**Comment by hennevogel** [comment]
There is no need to validate this with javascript. It's already done...
