### ISSUE TITLE
Roles authorization

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#903]
Steps to reproduce:
* create conference (say: `goto`)
* sign up two user `cfp_member` and `another_organizer`
* sign in with admin and assign `cfp_member` to `cfp` team and `another_organizer` to `organizer` team.
* sign in with `cfp_member` user
* go to roles page of goto conf: `http://localhost:3000/admin/conference/goto/roles`
* click on `users` button; page with go to organizers show page
* toggle `another_organizer` (it is crucial that you have two organizers)

You just removed an organizer from his own conference being in cfp team :sweat_smile:
You can also add any user to any team, edit any role (description).

**Comment by differentreality** [comment]
I will look into it.

**Comment by Rolence** [comment]
I did what you outlined above but didn't remove my organizer. Can you elaborate more on the bug!!

**Comment by sonalkr132** [comment]
![ezgif-1316420179](https://cloud.githubusercontent.com/assets/7680662/14077602/cbff026e-f50a-11e5-8b24-b55e143e56c9.gif)

**Comment by sonalkr132** [comment]
It is happening cause `authorize! @role, :toggle_user` is missing from `toggle_action` of `Admin::RolesControlle`

**Comment by differentreality** [comment]
Nice gif ;) 
I can confirm the issue.

**Comment by nishanthvijayan** [comment]
The issue seems to be caused by [this line](https://github.com/openSUSE/osem/blob/master/app%2Fmodels%2Fability.rb#L201)
:manage includes all actions on the object and so includes :toggle_user as well
and if there are multiple can rules on same action and object they are logically or'ed
So the [rule on toggle_user](https://github.com/openSUSE/osem/blob/master/app%2Fmodels%2Fability.rb#L207) becomes useless
and like @sonalkr132 mentioned there is no authorization check in both admin/roles_controller#toggle_user and admin/roles_controller#update
